"""Add password, confirm_password, and terms fields

Revision ID: eb06d317e317
Revises: 0607a743a31d
Create Date: 2026-01-15 22:33:28.699057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'eb06d317e317'
down_revision = '0607a743a31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IX_DepartmentId'))

    op.drop_table('Employees')
    op.drop_table('EmpContactDetails')
    op.drop_table('__MigrationHistory')
    op.drop_table('Emp')
    op.drop_table('Departments')
    op.drop_table('users')
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('confirm_password', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('terms', sa.Boolean(), nullable=True))
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.NUMERIC(precision=10, scale=0),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=8, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=8, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=sa.NUMERIC(precision=10, scale=0),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        batch_op.drop_column('terms')
        batch_op.drop_column('confirm_password')
        batch_op.drop_column('password')

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=80, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('dbo', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__users__3213E83F1B0907CE'))
    )
    op.create_table('Departments',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Name', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Location', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='PK_dbo.Departments')
    )
    op.create_table('Emp',
    sa.Column('EmployeeID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('FirstName', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('LastName', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Gender', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('EmployeeID', name=op.f('PK__Emp__7AD04FF1060DEAE8'))
    )
    op.create_table('__MigrationHistory',
    sa.Column('MigrationId', sa.NVARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('ContextKey', sa.NVARCHAR(length=300, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Model', mssql.VARBINARY(), autoincrement=False, nullable=False),
    sa.Column('ProductVersion', sa.NVARCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('MigrationId', 'ContextKey', name=op.f('PK_dbo.__MigrationHistory'))
    )
    op.create_table('EmpContactDetails',
    sa.Column('EmployeeID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Email', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Mobile', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('LandLine', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('EmployeeID', name=op.f('PK__EmpConta__7AD04FF109DE7BCC'))
    )
    op.create_table('Employees',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('FirstName', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('LastName', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Gender', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Salary', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('DepartmentId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('JobTitle', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['DepartmentId'], ['Departments.Id'], name=op.f('FK_dbo.Employees_dbo.Departments_DepartmentId'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id', name=op.f('PK_dbo.Employees'))
    )
    with op.batch_alter_table('Employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IX_DepartmentId'), ['DepartmentId'], unique=False)

    # ### end Alembic commands ###
